name: PetBuddy

on:
  push:
    branches:
      - version-I
  pull-request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Cocoapods
        run: sudo gem install cocoapods
      - name: Install Dependencies for iOS
        run: |
          npm install
          cd ios
          pod install
      - name: Check Xcode version
        run: xcodebuild -version
      - name: Build on iOS
        run: npx react-native build-ios
