name: PetBuddy

on:
  push:
    branches:
      - version-I

jobs:
  build-and-test:
    runs-on: macos-latest
    name: check workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Install Cocoapods
        run: sudo gem install cocoapods
      - name: Install Dependencies for iOS
        run: |
          cd ios
          pod install
      - name: Build on iOS
        run: npx react-native build-ios
